name: Generate README

on:
  push:
    branches:
      - test-actions

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate README
        uses: mikeschinkel/readme-merge@main
