name: Generate README

on:
  push:
    branches:
      - test-actions

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate README
        uses: mikeschinkel/readme-merge@0.0.15
        with:
          index_filepath: './md/_index.md'
          readme_dir: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}